version: '3'
services:
  app:
    image: calshankar/node-js:v1.0
    container_name: app-shankar
    ports:
      - "3000:3000"
    depends_on: ['fluentd', 'mongo']
    links:
      - mongo
    environment:
      MONGODB_URI: "mongodb://mongo:27017/passbook-offers"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: app-shankar
    networks:
      - EFK

  mongo:
    container_name: mongo
    image: mongo
    command: mongod --smallfiles
    volumes:
      - /tmp/data:/data/db
    ports:
      - "27017:27017"
    networks:
      - EFK

  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - elasticsearch
    expose:
      - "42185"
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - EFK
    depends_on: ['elasticsearch']

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${TAG}
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticdata:/usr/share/elasticsearch/data
    networks:
      - EFK

  kibana:
    image: docker.elastic.co/kibana/kibana:${TAG}
    environment:
      - ELASTICSEARCH_USERNAME=kibana
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
    container_name: kibana
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"
    networks:
      - EFK
    depends_on: ['elasticsearch']
  
  auditbeat:
    image: docker.elastic.co/beats/auditbeat:${TAG}
    container_name: auditbeat
    command: -e -E 'output.elasticsearch.password=${ELASTIC_PASSWORD}'
    cap_add: ['AUDIT_CONTROL', 'AUDIT_READ']
    # Auditbeat must run in the main process namespace.
    pid: host
    networks: ['EFK']
    depends_on: ['elasticsearch']

  filebeat:
    image: docker.elastic.co/beats/filebeat:${TAG}
    container_name: filebeat
    command: -e -E 'output.elasticsearch.password=${ELASTIC_PASSWORD}'
    # If the host system has logs at "/var/log", mount them at "/mnt/log"
    # inside the container, where Filebeat can find them.
    volumes: ['/var/log:/mnt/log:ro']
    networks: ['EFK']
    depends_on: ['elasticsearch', 'setup_filebeat']

  heartbeat:
    image: docker.elastic.co/beats/heartbeat:${TAG}
    container_name: heartbeat
    command: -e -E 'output.elasticsearch.password=${ELASTIC_PASSWORD}'
    networks: ['EFK']
    depends_on: ['elasticsearch', 'setup_heartbeat']

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:${TAG}
    container_name: metricbeat
    # The commented sections below enable Metricbeat to monitor the Docker host,
    # rather than the Metricbeat container. It's problematic with Docker for
    # Windows, however, since "/proc", "/sys" etc. don't exist on Windows.
    # The same likely applies to OSX (needs testing).
    volumes:
       - /proc:/hostfs/proc:ro
       - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
       - /:/hostfs:ro
    command: -e -E 'output.elasticsearch.password=${ELASTIC_PASSWORD}' # -system.hostfs=/hostfs
    networks: ['EFK']
    depends_on: ['elasticsearch', 'setup_metricbeat']

  packetbeat:
    image: docker.elastic.co/beats/packetbeat:${TAG}
    container_name: packetbeat
    # Packetbeat needs some elevated privileges to capture network traffic.
    # We'll grant them with POSIX capabilities.
    cap_add: ['NET_RAW', 'NET_ADMIN']
    # Use "host mode" networking to allow Packetbeat to capture traffic from
    # the real network interface on the host, rather than being isolated to the
    # container's virtual interface.
    network_mode: host
    # Since we did that, Packetbeat is not part of the "stack" Docker network
    # that the other containers are connected to, and thus can't resolve the
    # hostname "elasticsearch". Instead, we'll tell it to find Elasticsearch
    # on "localhost", which is the Docker host machine in this context.
    command: -e -E 'output.elasticsearch.hosts=["localhost:9200"]' -E 'output.elasticsearch.password=${ELASTIC_PASSWORD}'
    depends_on: ['elasticsearch']

  apm_server:
    image: docker.elastic.co/apm/apm-server:${TAG}
    container_name: apm_server
    ports: ['0.0.0.0:8200:8200']
    networks: ['EFK']
    command: -e -E 'apm-server.host=0.0.0.0:8200' -E 'output.elasticsearch.password=${ELASTIC_PASSWORD}'
    depends_on: ['elasticsearch','setup_apm_server']

  setup_kibana:
    image: centos:7
    container_name: setup_kibana
    volumes: ['./scripts/setup-kibana.sh:/usr/local/bin/setup-kibana.sh:ro']
    command: ['/bin/bash', '-c', 'cat /usr/local/bin/setup-kibana.sh | tr -d "\r" | bash']
    environment: ['ELASTIC_PASSWORD=${ELASTIC_PASSWORD}']
    networks: ['EFK']
    depends_on: ['elasticsearch']

  setup_auditbeat:
    image: docker.elastic.co/beats/auditbeat:${TAG}
    container_name: setup_auditbeat
    volumes: ['./scripts/setup-beat.sh:/usr/local/bin/setup-beat.sh:ro']
    command: ['/bin/bash', '-c', 'cat /usr/local/bin/setup-beat.sh | tr -d "\r" | bash -s auditbeat']
    environment: ['ELASTIC_PASSWORD=${ELASTIC_PASSWORD}']
    networks: ['EFK']
    depends_on: ['kibana']

  setup_filebeat:
    image: docker.elastic.co/beats/filebeat:${TAG}
    container_name: setup_filebeat
    volumes: ['./scripts/setup-beat.sh:/usr/local/bin/setup-beat.sh:ro']
    command: ['/bin/bash', '-c', 'cat /usr/local/bin/setup-beat.sh | tr -d "\r" | bash -s filebeat']
    environment: ['ELASTIC_PASSWORD=${ELASTIC_PASSWORD}']
    networks: ['EFK']
    depends_on: ['kibana']

  setup_heartbeat:
    image: docker.elastic.co/beats/heartbeat:${TAG}
    container_name: setup_heartbeat
    volumes: ['./scripts/setup-beat.sh:/usr/local/bin/setup-beat.sh:ro']
    command: ['/bin/bash', '-c', 'cat /usr/local/bin/setup-beat.sh | tr -d "\r" | bash -s heartbeat']
    environment: ['ELASTIC_PASSWORD=${ELASTIC_PASSWORD}']
    networks: ['EFK']
    depends_on: ['kibana']

  setup_metricbeat:
    image: docker.elastic.co/beats/metricbeat:${TAG}
    container_name: setup_metricbeat
    volumes: ['./scripts/setup-beat.sh:/usr/local/bin/setup-beat.sh:ro']
    command: ['/bin/bash', '-c', 'cat /usr/local/bin/setup-beat.sh | tr -d "\r" | bash -s metricbeat']
    environment: ['ELASTIC_PASSWORD=${ELASTIC_PASSWORD}']
    networks: ['EFK']
    depends_on: ['kibana']

  setup_packetbeat:
    image: docker.elastic.co/beats/packetbeat:${TAG}
    container_name: setup_packetbeat
    cap_add: ['NET_RAW', 'NET_ADMIN']
    volumes: ['./scripts/setup-beat.sh:/usr/local/bin/setup-beat.sh:ro']
    command: ['/bin/bash', '-c', 'cat /usr/local/bin/setup-beat.sh | tr -d "\r" | bash -s packetbeat']
    environment: ['ELASTIC_PASSWORD=${ELASTIC_PASSWORD}']
    networks: ['EFK']
    depends_on: ['kibana']

  setup_apm_server:
    image: docker.elastic.co/apm/apm-server:${TAG}
    container_name: setup_apm_server
    volumes: ['./scripts/setup-beat.sh:/usr/local/bin/setup-beat.sh:ro']
    command: ['/bin/bash', '-c', 'cat /usr/local/bin/setup-beat.sh | tr -d "\r" | bash -s apm-server']
    environment: ['ELASTIC_PASSWORD=${ELASTIC_PASSWORD}']
    networks: ['EFK']
    depends_on: ['elasticsearch','kibana']

networks: {EFK: {}}
volumes:
  elasticdata:
    driver: local
